version: "3"

tasks:
  generate:
    aliases:
      - gen
    description: "Generate protobuf code"
    cmds:
      - protoc -I proto proto/user/user.proto --go_out=./clients --go_opt=paths=source_relative --go-grpc_out=./clients --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/task/task.proto --go_out=./clients --go_opt=paths=source_relative --go-grpc_out=./clients --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/status/status.proto --go_out=./clients --go_opt=paths=source_relative --go-grpc_out=./clients --go-grpc_opt=paths=source_relative