version: "3"

tasks:
  generate:
    aliases:
      - gen
    description: "Generate protobuf code"

    cmds:
      - protoc -I proto proto/auth/auth.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative